### ISSUE TITLE
kzbg "disturbance" treatment is missing

### ISSUE THREAD

**Issue by adamtclark** [nutnetadmin/dragnet-data-tracker#107]
In the file "comb-by-plot-drag-diversity_2024-07-27.csv", there don't seem to be any rows for "just" the "Disturbance" treatment.

**Comment by nutnetadmin** [comment]
I went back and checked the plan (attached) for the site, and I don't see any "just disturbance" plots included there - is that not correct? Is this maybe an outdated site plan? It's an easy fix in the database if I need re-assign some plots to different treatments!
[DRAGNet-site-info-KZBG_2022.xls](https://github.com/user-attachments/files/16421155/DRAGNet-site-info-KZBG_2022.xls)

**Comment by nutnetadmin** [comment]
Updated the plot treatments in the database .
