### ISSUE TITLE
Import new sampling data: Ainsdale Dune Slacks (ains_dn.uk) 2023 (Yr 1)

### ISSUE THREAD

**Issue by ingridslette** [nutnetadmin/dragnet-data-tracker#76]

**Comment by ingridslette** [comment]
Also need to update plot designations, as treatments have changed from what was initially planned in year 0. Site was not able to apply nutrients, but was able to install fencing (for inclusion in NutNet).

**Comment by nutnetadmin** [comment]
uploaded with script import-ains_dn-2023.sql
